spring:
  datasource:
    url:  jdbc:mysql://localhost/stub?useSSL=false
    username: stubadmin
    password: stubad
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9898

stub:
  notmatched:
    birthday: 20000101

flyway:
  locations: db/migration

---
spring:
    profiles: LOCAL
flyway:
  locations: local/db/migration

---
spring:
    profiles: DEV1
flyway:
  locations: dev1/db/migration

---
spring:
    profiles: DEV2
flyway:
  locations: dev2/db/migration