spring:
  datasource:
      url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
      driverClassName: org.h2.Driver
  jpa:
    # show-sql: true
    hibernate.ddl-auto: validate
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 9090

stub:
  notmatched:
    birthday: 20000101 # format yyyyMMdd
  create_amount: 100 #max 999
card:
  point:
    amount: 20000 # only number
    expiration_date: 20180403000000 # format yyyyMMddHHmmss
    expiration_amount: 0 # only number
  password: GT20170524

flyway:
  locations: db/migration

---

spring:
  profiles: MYSQL
  datasource:
    url:  jdbc:mysql://localhost/stub?useSSL=false
    username: stubadmin
    password: stubad
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: DEV1
flyway:
  locations: dev1/db/migration

---

spring:
  profiles: IT2
flyway:
  locations: it2/db/migration

---

spring:
  profiles: VALID
flyway:
  locations: valid/db/migration
