spring:
  datasource:
    url:  jdbc:mysql://localhost/stub?useSSL=false
    username: stubadmin
    password: stubad
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
